stages:
  - prepare
  - gateware
  - software

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2020.2/Vivado/2020.2
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2020.2/Vitis/2020.2
  CI_REGISTRY: mohs.dhcp.lbl.gov
  CONTAINER_IMAGE: $CI_REGISTRY/xilinx_env
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

image: $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME

services:
  - name: mohs.dhcp.lbl.gov/docker:20.10.12-dind
    command: ["--insecure-registry", "mohs.dhcp.lbl.gov"]
    alias: docker

include:
  - local: .gitlab/ci/build-image.gitlab-ci.yml

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gw_hsd_zcu111:
  before_script:
    - cd gateware/syn/hsd_zcu111 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make hsd_zcu111_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/hsd_zcu111/hsd_zcu111_top.bit
      - gateware/syn/hsd_zcu111/_xilinx/hsd_zcu111_top/*.runs/impl_1/*.rpt
      - gateware/syn/hsd_zcu111/system.xsa

gw_hsd_zcu208:
  before_script:
    - cd gateware/syn/hsd_zcu208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make hsd_zcu208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/hsd_zcu208/hsd_zcu208_top.bit
      - gateware/syn/hsd_zcu208/_xilinx/hsd_zcu208_top/*.runs/impl_1/*.rpt
      - gateware/syn/hsd_zcu208/system.xsa

gw_bcm_zcu111:
  before_script:
    - cd gateware/syn/bcm_zcu111 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make bcm_zcu111_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/bcm_zcu111/bcm_zcu111_top.bit
      - gateware/syn/bcm_zcu111/_xilinx/bcm_zcu111_top/*.runs/impl_1/*.rpt
      - gateware/syn/bcm_zcu111/system.xsa

gw_bpm_zcu208:
  before_script:
    - cd gateware/syn/bpm_zcu208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make bpm_zcu208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/bpm_zcu208/bpm_zcu208_top.bit
      - gateware/syn/bpm_zcu208/_xilinx/bpm_zcu208_top/*.runs/impl_1/*.rpt
      - gateware/syn/bpm_zcu208/system.xsa

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
sw_hsd_zcu111:
  before_script:
    - cd software/app/hsd
  stage: software
  script:
    - make TARGET=hsd_zcu111 clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH time make TARGET=hsd_zcu111
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_hsd_zcu111
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/hsd/hsd_zcu111/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/hsd/hsd_zcu111/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/hsd/hsd_zcu111.elf
      - software/app/hsd/BOOT.bin

sw_hsd_zcu208:
  before_script:
    - cd software/app/hsd
  stage: software
  script:
    - make TARGET=hsd_zcu208 clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH time make TARGET=hsd_zcu208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_hsd_zcu208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/hsd/hsd_zcu208/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/hsd/hsd_zcu208/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/hsd/hsd_zcu208.elf
      - software/app/hsd/BOOT.bin

sw_bcm_zcu111:
  before_script:
    - cd software/app/bcm
  stage: software
  script:
    - make TARGET=bcm_zcu111 clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH time make TARGET=bcm_zcu111
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_bcm_zcu111
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/bcm/bcm_zcu111/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/bcm/bcm_zcu111/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/bcm/bcm_zcu111.elf
      - software/app/bcm/BOOT.bin

sw_bpm_zcu208:
  before_script:
    - cd software/app/bpm
  stage: software
  script:
    - make TARGET=bpm_zcu208 clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH time make TARGET=bpm_zcu208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_bpm_zcu208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/bpm/bpm_zcu208/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/bpm/bpm_zcu208/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/bpm/bpm_zcu208.elf
      - software/app/bpm/BOOT.bin
