stages:
  - prepare
  - gateware
  - software

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2020.2/Vivado/2020.2
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2020.2/Vitis/2020.2
  CI_REGISTRY: mohs.dhcp.lbl.gov
  CONTAINER_IMAGE: $CI_REGISTRY/testing_base_bullseye
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

image: $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME

services:
  - name: mohs.dhcp.lbl.gov/docker:20.10.12-dind
    command: ["--insecure-registry", "mohs.dhcp.lbl.gov"]
    alias: docker

include:
  - local: .gitlab/ci/build-image.gitlab-ci.yml

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gateware_zcu111:
  before_script:
    - cd gateware/syn/hsd_zcu111 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make hsd_zcu111_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/hsd_zcu111/hsd_zcu111_top.bit
      - gateware/syn/hsd_zcu111/_xilinx/hsd_zcu111_top/*.runs/impl_1/*.rpt
      - gateware/syn/hsd_zcu111/system.xsa

gateware_zcu208:
  before_script:
    - cd gateware/syn/hsd_zcu208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make hsd_zcu208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/hsd_zcu208/hsd_zcu208_top.bit
      - gateware/syn/hsd_zcu208/_xilinx/hsd_zcu208_top/*.runs/impl_1/*.rpt
      - gateware/syn/hsd_zcu208/system.xsa

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
software_zcu111:
  before_script:
    - cd software/hsd
  stage: software
  script:
    - make clean && PATH=$XILINX_VITIS/bin:$PATH time make TARGET=zcu111
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - "gateware_zcu111"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/hsd/HighSpeedDigitizer/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/hsd/HighSpeedDigitizer/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/hsd/HighSpeedDigitizer.elf
      - software/hsd/BOOT.bin

software_zcu208:
  before_script:
    - cd software/hsd
  stage: software
  script:
    - make clean && PATH=$XILINX_VITIS/bin:$PATH time make TARGET=zcu208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - "gateware_zcu208"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/hsd/HighSpeedDigitizer/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/hsd/HighSpeedDigitizer/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/hsd/HighSpeedDigitizer.elf
      - software/hsd/BOOT.bin
