/*
 * Additions for beam position monitor
 */

#ifndef _BEAM_POSITION_MONITOR_PROTOCOL_
#define _BEAM_POSITION_MONITOR_PROTOCOL_

#  define BPM_PROTOCOL_CMD_LONGOUT_GENERIC_LOB_THRSH              0x20
#  define BPM_PROTOCOL_CMD_LONGOUT_GENERIC_TBT_SUM_SHIFT          0x21
#  define BPM_PROTOCOL_CMD_LONGOUT_GENERIC_MT_SUM_SHIFT           0x22
#  define BPM_PROTOCOL_CMD_LONGOUT_GENERIC_BUTTON_DSP             0x23
#  define BPM_PROTOCOL_CMD_LONGOUT_GENERIC_AUTOTRIM_CTL           0x24
#  define BPM_PROTOCOL_CMD_LONGOUT_GENERIC_AUTOTRIM_THRS          0x25
#  define BPM_PROTOCOL_CMD_LONGOUT_GENERIC_AUTOTRIM_FILT_SHFT     0x26

// For compatibility
#  define BPM_PROTOCOL_CMD_LONGOUT_LOB_THRSH                      (BPM_PROTOCOL_CMD_LONGOUT_GENERIC_LOB_THRSH)
#  define BPM_PROTOCOL_CMD_LONGOUT_TBT_SUM_SHIFT                  (BPM_PROTOCOL_CMD_LONGOUT_GENERIC_TBT_SUM_SHIFT)
#  define BPM_PROTOCOL_CMD_LONGOUT_MT_SUM_SHIFT                   (BPM_PROTOCOL_CMD_LONGOUT_GENERIC_MT_SUM_SHIFT)

# define HSD_PROTOCOL_CMD_LONGOUT_LO_TRIM                       0x0080

#endif /* _BEAM_POSITION_MONITOR_PROTOCOL_ */
