/*
 * Additions for beam position monitor
 */

#ifndef _BEAM_POSITION_MONITOR_PROTOCOL_
#define _BEAM_POSITION_MONITOR_PROTOCOL_

#define BPM_PROTOCOL_CMD_LONGOUT_LOB_THRSH        0x20
#define BPM_PROTOCOL_CMD_LONGOUT_TBT_SUM_SHIFT    0x21
#define BPM_PROTOCOL_CMD_LONGOUT_MT_SUM_SHIFT     0x22

#endif /* _BEAM_POSITION_MONITOR_PROTOCOL_ */
